const apiBase='https://foxyyyyyy-qhuk.onrender.com';
const apiUrl=path=>`${apiBase}${path}`;
const nativeFetch=window.fetch.bind(window);
window.fetch=(input,...options)=>nativeFetch(typeof input==='string'&&input.startsWith('/api/')?apiUrl(input):input,...options);
const state={channels:[],films:[],filmsCount:0,filmsLoaded:false,channelsRevision:'',filmsRevision:'',view:'channels',category:'all',search:'',sort:'name',editing:-1};
const $=selector=>document.querySelector(selector);
const fileInput=$('#fileInput'), emptyFileInput=$('#emptyFileInput'), dropZone=$('#dropZone');
function parseAttributes(text){const attrs={}; const pattern=/([\w-]+)="([^"]*)"/g; let match; while((match=pattern.exec(text))) attrs[match[1]]=match[2]; return attrs;}
function parseM3U(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean); const result=[]; for(let index=0;index<lines.length;index++){if(!lines[index].startsWith('#EXTINF')) continue; const info=lines[index]; const comma=info.indexOf(','); const attrs=parseAttributes(info.slice(0,comma)); const name=comma>-1?info.slice(comma+1).trim():'Canal sem nome'; const url=lines.slice(index+1).find(line=>!line.startsWith('#'))||''; if(url){result.push({name,group:attrs['group-title']||'Sem categoria',logo:attrs['tvg-logo']||'',id:attrs['tvg-id']||'',url});}} return result;}
function loadText(text,fileName='playlist.m3u'){state.channels=parseM3U(text); state.view='channels'; state.category='all'; state.search=''; $('#searchInput').value=''; update(); $('#statusText').textContent=`${fileName} carregada`;}
async function loadServerPlaylist(){if(location.protocol==='file:'){ $('#statusText').textContent='Abra pelo servidor em http://localhost:3000'; return; } try{const response=await fetch('/api/catalog?list=channels',{cache:'no-store'}); if(!response.ok)throw new Error('Não foi possível carregar a playlist.'); const data=await response.json(); state.channels=Array.isArray(data.channels)?data.channels:[]; state.filmsCount=Number(data.filmsCount)||0; state.channelsRevision=data.channelsRevision||''; state.filmsRevision=data.filmsRevision||''; state.filmsLoaded=false; state.films=[]; state.view='channels'; state.category='all'; state.search=''; update(); $('#statusText').textContent=state.channels.length?`${data.source||'Playlist'} carregada`:'Playlist vazia';}catch(error){$('#statusText').textContent=error.message;}}
async function loadFilms(){if(state.filmsLoaded)return; $('#statusText').textContent='Carregando filmes...'; try{const response=await fetch('/api/catalog?list=films',{cache:'no-store'}); if(!response.ok)throw new Error('Não foi possível carregar filmes.m3u.'); const data=await response.json(); state.films=Array.isArray(data.films)?data.films:[]; state.filmsCount=state.films.length; state.filmsRevision=data.filmsRevision||state.filmsRevision; state.filmsLoaded=true; update(); $('#statusText').textContent=state.films.length?`${data.filmsSource||'filmes.m3u'} carregada`:'filmes.m3u vazia';}catch(error){$('#statusText').textContent=error.message;}}
async function checkForUpdates(){if(location.protocol==='file:')return; try{const response=await fetch('/api/catalog?list=meta',{cache:'no-store'}); if(!response.ok)return; const meta=await response.json(); if(meta.channelsRevision!==state.channelsRevision){await loadServerPlaylist();return;} if(meta.filmsRevision!==state.filmsRevision){state.filmsRevision=meta.filmsRevision;state.filmsCount=meta.filmsCount;state.filmsLoaded=false;state.films=[];update(); if(state.view==='films')await loadFilms(); else $('#statusText').textContent='Nova playlist de filmes detectada';}}catch(error){}}
function readFile(file){if(!file)return; const reader=new FileReader(); reader.onload=event=>loadText(event.target.result,file.name); reader.readAsText(file);}
function update(){const channels=state.view==='films'?state.films:state.channels; $('#totalCount').textContent=channels.length; $('#heroCount').textContent=channels.length; $('#categoryCount').textContent=new Set(channels.map(channel=>channel.group)).size; $('#filmsTabCount').textContent=state.filmsLoaded?state.films.length:state.filmsCount; $('#catalogTitle').textContent=state.view==='films'?'Filmes da playlist':'Canais da playlist'; const withLogo=channels.filter(channel=>channel.logo).length; $('#logoCount').textContent=channels.length?`${Math.round(withLogo/channels.length*100)}%`:'0%'; const ready=channels.length>0; ['exportButton','dedupeButton','clearButton','searchInput','sortSelect'].forEach(id=>{$(`#${id}`).disabled=!ready}); $('#sortSelect').value=state.sort; $('#emptyState').hidden=ready; $('#channelList').hidden=!ready; $('#channelsTab').classList.toggle('active',state.view==='channels'); $('#filmsTab').classList.toggle('active',state.view==='films'); renderCategories(); renderChannels();}
fileInput.onchange=event=>readFile(event.target.files[0]); emptyFileInput.onchange=event=>readFile(event.target.files[0]); $('#channelsTab').onclick=()=>{state.view='channels';state.category='all';state.search='';$('#searchInput').value='';update();}; $('#filmsTab').onclick=async()=>{state.view='films';state.category='all';state.search='';$('#searchInput').value='';update();await loadFilms();}; $('#exportButton').onclick=exportM3U;
function renderCategories(){const channels=state.view==='films'?state.films:state.channels; const groups={}; channels.forEach(channel=>groups[channel.group]=(groups[channel.group]||0)+1); const list=$('#categoryList'); list.innerHTML=''; const all=document.createElement('button'); all.className=`category ${state.category==='all'?'active':''}`; all.dataset.category='all'; all.innerHTML=`<span>Todos os ${state.view==='films'?'filmes':'canais'}</span><b>${channels.length}</b>`; list.append(all); Object.entries(groups).sort((a,b)=>a[0].localeCompare(b[0])).forEach(([group,count])=>{const button=document.createElement('button'); button.className=`category ${state.category===group?'active':''}`; button.dataset.category=group; button.innerHTML=`<span>${escapeHtml(group)}</span><b>${count}</b>`; list.append(button);}); list.querySelectorAll('.category').forEach(button=>button.onclick=()=>{state.category=button.dataset.category;update();});}
function visibleChannels(){const channels=state.view==='films'?state.films:state.channels; const query=state.search.toLowerCase(); const visible=channels.map((channel,index)=>({...channel,index})).filter(channel=>(state.category==='all'||channel.group===state.category)&&(!query||`${channel.name} ${channel.group}`.toLowerCase().includes(query))); return visible.sort((first,second)=>{if(state.sort==='group')return first.group.localeCompare(second.group)||first.name.localeCompare(second.name); if(state.sort==='logo')return Number(Boolean(second.logo))-Number(Boolean(first.logo))||first.name.localeCompare(second.name); const result=first.name.localeCompare(second.name); return state.sort==='name-desc'?-result:result;});}
function renderChannels(){const list=$('#channelList'); list.innerHTML=''; const visible=visibleChannels(); if(!visible.length){list.innerHTML='<div class="empty-state"><h3>Nenhum canal encontrado</h3><p>Ajuste a busca ou escolha outra categoria.</p></div>';return;} const shown=visible.slice(0,120); shown.forEach(channel=>{const item=document.createElement('article'); item.className='channel'; const logo=channel.logo?`<img class="channel-logo" src="${escapeAttr(channel.logo)}" alt="" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'grid\'">`:'<div class="channel-logo" style="display:none"></div>'; item.innerHTML=`${logo}<div class="channel-logo no-logo" ${channel.logo?'style="display:none"':''}>TV</div><div><div class="channel-name" title="${escapeAttr(channel.name)}">${escapeHtml(channel.name)}</div><div class="channel-group">${escapeHtml(channel.group)}</div></div><div class="channel-actions"><button class="icon-button edit" title="Editar">✎</button><button class="icon-button remove" title="Remover">×</button></div>`; item.querySelector('.edit').onclick=()=>openEditor(channel.index); item.querySelector('.remove').onclick=()=>{state.channels.splice(channel.index,1);update();}; list.append(item);}); if(visible.length>shown.length){const more=document.createElement('button'); more.className='load-more'; more.textContent=`Carregar mais ${Math.min(120,visible.length-shown.length)} canais`; more.onclick=()=>{const current=list.querySelectorAll('.channel').length; visible.slice(current,current+120).forEach(channel=>{const item=document.createElement('article'); item.className='channel'; const logo=channel.logo?`<img class="channel-logo" src="${escapeAttr(channel.logo)}" alt="" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'grid\'">`:'<div class="channel-logo" style="display:none"></div>'; item.innerHTML=`${logo}<div class="channel-logo no-logo" ${channel.logo?'style="display:none"':''}>TV</div><div><div class="channel-name" title="${escapeAttr(channel.name)}">${escapeHtml(channel.name)}</div><div class="channel-group">${escapeHtml(channel.group)}</div></div><div class="channel-actions"><button class="icon-button edit" title="Editar">✎</button><button class="icon-button remove" title="Remover">×</button></div>`; item.querySelector('.edit').onclick=()=>openEditor(channel.index); item.querySelector('.remove').onclick=()=>{state.channels.splice(channel.index,1);update();}; list.insertBefore(item,more);}); if(list.querySelectorAll('.channel').length>=visible.length)more.remove(); else more.textContent=`Carregar mais ${Math.min(120,visible.length-list.querySelectorAll('.channel').length)} canais`;}; list.append(more);}}
function openEditor(index){const channel=state.channels[index]; state.editing=index; $('#dialogTitle').textContent=channel.name; $('#nameField').value=channel.name; $('#groupField').value=channel.group; $('#urlField').value=channel.url; $('#logoField').value=channel.logo; $('#editDialog').showModal();}
$('#editForm').addEventListener('submit',event=>{event.preventDefault(); const channel=state.channels[state.editing]; channel.name=$('#nameField').value.trim(); channel.group=$('#groupField').value.trim()||'Sem categoria'; channel.url=$('#urlField').value.trim(); channel.logo=$('#logoField').value.trim(); $('#editDialog').close();update();});
function exportM3U(){const lines=['#EXTM3U']; const channels=state.view==='films'?state.films:state.channels; channels.forEach(channel=>{const attrs=[`tvg-id="${channel.id||''}"`,`tvg-logo="${channel.logo||''}"`,`group-title="${channel.group||'Sem categoria'}"`]; lines.push(`#EXTINF:-1 ${attrs.join(' ')},${channel.name}`,channel.url);}); const blob=new Blob([lines.join('\n')+'\n'],{type:'audio/x-mpegurl'}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=state.view==='films'?'filmes.m3u':'playlist-iptv.m3u'; link.click(); URL.revokeObjectURL(link.href);}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));} function escapeAttr(value){return escapeHtml(value);}
fileInput.onchange=event=>readFile(event.target.files[0]); emptyFileInput.onchange=event=>readFile(event.target.files[0]); $('#channelsTab').onclick=()=>{state.view='channels';state.category='all';state.search='';$('#searchInput').value='';update();}; $('#filmsTab').onclick=()=>{state.view='films';state.category='all';state.search='';$('#searchInput').value='';update();}; $('#exportButton').onclick=exportM3U; $('#searchInput').oninput=event=>{state.search=event.target.value;renderChannels();}; $('#clearButton').onclick=()=>{if(state.view==='films')state.films=[];else state.channels=[];update();$('#statusText').textContent='Nenhuma lista carregada';}; $('#dedupeButton').onclick=()=>{const seen=new Set();const keyList=state.view==='films'?'films':'channels';state[keyList]=state[keyList].filter(channel=>{const key=channel.url.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});update();}; dropZone.ondragover=event=>{event.preventDefault();dropZone.classList.add('dragging');}; dropZone.ondragleave=()=>dropZone.classList.remove('dragging'); dropZone.ondrop=event=>{event.preventDefault();dropZone.classList.remove('dragging');readFile(event.dataTransfer.files[0]);}; update(); loadServerPlaylist();
